# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
common_docker: &common_docker_anchor
  - image: circleci/node:12.13.0

common_steps: &common_steps_anchor
  - checkout:
      path: ~/repo

  - restore_cache:
      keys:
        - v1-dependencies-{{ checksum "package.json" }}
        - v1-dependencies-

  - run: yarn install

  - save_cache:
      paths:
        - node_modules
      key: v1-dependencies-{{ checksum "package.json" }}

  - run: yarn coverage
  - run: yarn lint
  - run: yarn typecheck

jobs:
  build-array:
    docker: *common_docker_anchor
    working_directory: ~/repo/packages/array
    steps: *common_steps_anchor

  build-composition:
    docker: *common_docker_anchor
    working_directory: ~/repo/packages/composition
    steps: *common_steps_anchor

  build-dispatch:
    docker: *common_docker_anchor
    working_directory: ~/repo/packages/dispatch
    steps: *common_steps_anchor

  build-error:
    docker: *common_docker_anchor
    working_directory: ~/repo/packages/error
    steps: *common_steps_anchor

  build-multimethod:
    docker: *common_docker_anchor
    working_directory: ~/repo/packages/multimethod
    steps: *common_steps_anchor

  build-server:
    docker: *common_docker_anchor
    working_directory: ~/repo/packages/server
    steps: *common_steps_anchor

  build-string:
    docker: *common_docker_anchor
    working_directory: ~/repo/packages/string
    steps: *common_steps_anchor

  build-worker:
    docker: *common_docker_anchor
    working_directory: ~/repo/packages/worker
    steps: *common_steps_anchor

  build-arrows:
    docker: *common_docker_anchor
    working_directory: ~/repo/packages/arrows
    steps: *common_steps_anchor

workflows:
  version: 2
  build:
    jobs:
      - build-array
      - build-composition
      - build-dispatch
      - build-error
      - build-multimethod
      # - build-server
      - build-string
      - build-worker
      - build-arrows
