import clear from './clear';
import filter from './filter';
import insert from './insert';
import map from './map';
import pop from './pop';
import push from './push';
import reduce from './reduce';
import reduceRight from './reduceRight';
import remove from './remove';
import reverse from './reverse';
import set from './set';
import shift from './shift';
import size from './size';
import sort from './sort';
import unshift from './unshift';
export { clear, filter, insert, map, pop, push, reduce, reduceRight, remove, reverse, set, shift, size, sort, unshift, };
declare const _default: {
    clear: (arr: any) => any[];
    filter: (fn: any) => (arr: any) => any;
    insert: (index: any, value: any) => (arr: any) => any;
    map: (fn: any) => (arr: any) => any;
    pop: (arr: any) => any;
    push: (value: any) => (arr: any) => any;
    reduce: (fn: any, initialValue: any) => (arr: any) => any;
    reduceRight: (fn: any, initialValue: any) => (arr: any) => any;
    remove: (index: any) => (arr: any) => any;
    reverse: (arr: any) => any;
    set: (index: any, value: any) => (arr: any) => any[];
    shift: (arr: any) => any;
    size: (arr: any) => any;
    sort: (fn?: (a: any, b: any) => number) => (arr: any[]) => any[];
    unshift: (value: any) => (arr: any) => any[];
};
export default _default;
